/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CryptocurrencyService } from "../cryptocurrency.service";
import { CryptocurrencyCreateInput } from "./CryptocurrencyCreateInput";
import { Cryptocurrency } from "./Cryptocurrency";
import { CryptocurrencyFindManyArgs } from "./CryptocurrencyFindManyArgs";
import { CryptocurrencyWhereUniqueInput } from "./CryptocurrencyWhereUniqueInput";
import { CryptocurrencyUpdateInput } from "./CryptocurrencyUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";
import { WalletFindManyArgs } from "../../wallet/base/WalletFindManyArgs";
import { Wallet } from "../../wallet/base/Wallet";
import { WalletWhereUniqueInput } from "../../wallet/base/WalletWhereUniqueInput";

export class CryptocurrencyControllerBase {
  constructor(protected readonly service: CryptocurrencyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Cryptocurrency })
  async createCryptocurrency(
    @common.Body() data: CryptocurrencyCreateInput
  ): Promise<Cryptocurrency> {
    return await this.service.createCryptocurrency({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Cryptocurrency] })
  @ApiNestedQuery(CryptocurrencyFindManyArgs)
  async cryptocurrencies(
    @common.Req() request: Request
  ): Promise<Cryptocurrency[]> {
    const args = plainToClass(CryptocurrencyFindManyArgs, request.query);
    return this.service.cryptocurrencies({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async cryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Cryptocurrency | null> {
    const result = await this.service.cryptocurrency({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        symbolField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() data: CryptocurrencyUpdateInput
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.updateCryptocurrency({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Cryptocurrency })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCryptocurrency(
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Cryptocurrency | null> {
    try {
      return await this.service.deleteCryptocurrency({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          name: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        amount: true,
        createdAt: true,

        cryptocurrency: {
          select: {
            id: true,
          },
        },

        fromWallet: true,
        fromWalletId: true,
        fromWalletReference: true,
        id: true,
        status: true,
        timestamp: true,
        toWallet: true,
        toWalletId: true,
        toWalletReference: true,
        transactionType: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/wallets")
  @ApiNestedQuery(WalletFindManyArgs)
  async findWallets(
    @common.Req() request: Request,
    @common.Param() params: CryptocurrencyWhereUniqueInput
  ): Promise<Wallet[]> {
    const query = plainToClass(WalletFindManyArgs, request.query);
    const results = await this.service.findWallets(params.id, {
      ...query,
      select: {
        address: true,
        balance: true,
        createdAt: true,

        cryptocurrency: {
          select: {
            id: true,
          },
        },

        fromWallet: true,
        id: true,
        toWallet: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/wallets")
  async connectWallets(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: WalletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wallets: {
        connect: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/wallets")
  async updateWallets(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: WalletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wallets: {
        set: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/wallets")
  async disconnectWallets(
    @common.Param() params: CryptocurrencyWhereUniqueInput,
    @common.Body() body: WalletWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      wallets: {
        disconnect: body,
      },
    };
    await this.service.updateCryptocurrency({
      where: params,
      data,
      select: { id: true },
    });
  }
}
